language: python
python:
 - 3.6

sudo: required
services:
  - docker

cache: pip

addons:
  apt:
    packages:
      - libssl-dev
      - python3-dev

before_script:
  - pip install coala-bears
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - coala --non-interactive -V
  - python -m pytest tests/ --cov plugins/ --cov-fail-under=100
  - docker build -t "corobo" .
  - docker images
  - codecov

notifications:
  email: false
