language: python
python:
 - 3.6

addons:
  apt:
    packages:
      - libssl-dev
      - python3-dev

before_script:
  - pip install coala-bears
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script: 
  - coala --non-interactive -V
  - python -m pytest --cov tests/

notifications:
  email: false
